## Consider the below code to answer further questions:

In [67]:
import numpy as np

list_ = ['1','2','3','4','5']

array_list = np.array(object = list_)

## Queston 1 : Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables
---

In [47]:
type(list_)

list

In [48]:
type(array_list)

numpy.ndarray

Yes, there is a difference in the data type of list_ and array_list.

list_ is a Python list, while array_list is a NumPy array.

## Question 2: Write a code to print the data type of each and every element of both the variables list_ and array_list.
---

In [52]:
for i in list_:
    print(i,type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [53]:
for i in array_list:
    print(i,type(i))

1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


## Question 3: Considering the following changes in the variable, array_list:

In [69]:
list_

['1', '2', '3', '4', '5']

In [71]:
array_list = np.array(object = list_, dtype = int)

In [61]:
array_list

array([1, 2, 3, 4, 5])

## Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_and array_list.
---

Yes, there will be a difference in the data types of the elements present in list_ and array_list. Initially, array_list is a NumPy array with string values (dtype='<U1'), and then it is converted to a new NumPy array with an integer data type (dtype=int).

To print the data types of each element in both variables, you can iterate over the elements and use the type()

This code will iterate over each element in list_ and array_list and print the data type of each element on separate lines.

Initially, the elements in list_ are strings since they are enclosed in quotes ('1', '2', '3', '4', '5'). After converting list_ to a NumPy array with dtype='<U1', the elements in array_list are also strings.

However, when array_list is converted to a new NumPy array with dtype=int, the elements are cast to integers. Therefore, the elements in the final array_list have a data type of int.

Keep in mind that during the conversion from strings to integers, if any of the elements in list_ cannot be converted to an integer, it will raise a ValueError.

In [73]:
for i in list_:
    print(i,type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [75]:
for i in array_list:
    print(i,type(array_list))

1 <class 'numpy.ndarray'>
2 <class 'numpy.ndarray'>
3 <class 'numpy.ndarray'>
4 <class 'numpy.ndarray'>
5 <class 'numpy.ndarray'>


## Consider the below code to answer further questions:

In [1]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Question 4: Write a code to find the following characteristics of variable, num_array:
### 1. shape
### 2. size
---

In [2]:
num_array.shape

(2, 3)

In [3]:
num_array.size

6

## Question 5: Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

### [Hint: The size of the array will be 9 and the shape will be (3,3).]

---

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Question 6: Create an identity matrix of shape (5,5) using numpy functions?

### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
---

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])